name: Sync to S3

on:
  push:
    branches:
      - master

env:
  DO-REGION: sgp1
  DO-URL: proginth
  S3_ACCESS_KEY : ${{ secrets.AWS_ACCESS_KEY_ID }}
  S3_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Change relative path to absolute path
        run: sed -i -e 's+../media/+https://proginth.sgp1.cdn.digitaloceanspaces.com/solutions/media/+g' *
        working-directory: ./md

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.2.0
        with:
          provider: digitalocean
          region: 'sgp1'
          access_key: ${{ secrets.S3_ACCESS_KEY }}
          secret_key: ${{ secrets.S3_SECRET_KEY }}

      - name: Copy files to S3 with the AWS CLI
        run: |
          s3cmd sync --recursive --acl-public . s3://proginth/solutions --exclude "*" --include "md/*" --include "media/*"
